repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.1
  hooks:
    - id: ruff
      args: ["--fix", "--output-format=full"]
    - id: ruff-format
- repo: https://github.com/MarcoGorelli/madforhooks
  rev: 0.3.0
  hooks:
    - id: no-print-statements
- repo: local
  hooks:
    - id: no-relative-imports
      name: No relative imports
      entry: from \.[\.\w]* import
      types: [python]
      language: pygrep
