name: cge-modeling
channels:
  - conda-forge
dependencies:
  # Core dependencies
  - python=3.12
  - pip
  - numpy
  - scipy
  - sympy
  - pandas
  - numba
  - pytensor
  - tqdm
  - numba-progress
  - fastprogress
  - matplotlib
  - jax
  - joblib

  - pip:
      - texttable
      - latextable
      - squarify
      - sympytensor
