ACTIVITIES = [
    "Paddy rice",
    "Wheat",
    "Cereal grains nec",
    "Vegetables, fruit, nuts",
    "Oil seeds",
    "Sugar cane, sugar beet",
    "Plant-based fibers",
    "Crops nec",
    "Bovine cattle, sheep and goats, horses",
    "Animal products nec",
    "Raw milk",
    "Wool, silk-worm cocoons",
    "Forestry",
    "Fishing",
    "Coal",
    "Oil",
    "Gas",
    "Other Extraction (formerly omn Minerals nec)",
    "Bovine meat products",
    "Meat products nec",
    "Vegetable oils and fats",
    "Dairy products",
    "Processed rice",
    "Sugar",
    "Food products nec",
    "Beverages and tobacco products",
    "Textiles",
    "Wearing apparel",
    "Leather products",
    "Wood products",
    "Paper products, publishing",
    "Petroleum, coal products",
    "Chemical products",
    "Basic pharmaceutical products",
    "Rubber and plastic products",
    "Mineral products nec",
    "Ferrous metals",
    "Metals nec",
    "Metal products",
    "Computer, electronic and optical products",
    "Electrical equipment",
    "Machinery and equipment nec",
    "Motor vehicles and parts",
    "Transport equipment nec",
    "Manufactures nec",
    "Electricity transmission and distribution",
    "Gas manufacture, distribution",
    "Water",
    "Construction",
    "Trade",
    "Accommodation, Food and service activities",
    "Transport nec",
    "Water transport",
    "Air transport",
    "Warehousing and support activities",
    "Communication",
    "Financial services nec",
    "Insurance (formerly isr)",
    "Real estate activities",
    "Business services nec",
    "Recreational and other services",
    "Public Administration and defense",
    "Education",
    "Human health and social work activities",
    "Dwellings",
    "Nuclear power",
    "Coal power baseload",
    "Gas power baseload",
    "Wind power",
    "Hydro power baseload",
    "Oil power baseload",
    "Other baseload",
    "Gas power peakload",
    "Hydro power peakload",
    "Oil power peakload",
    "Solar power",
]
COMMODITIES = ACTIVITIES.copy()

MARGIN_ACTIVITIES = ["Transport nec", "Water transport", "Air transport"]

FACTORS = ["Capital", "Labor", "Natural resources", "Electricity"]

INSTITUTIONS = ["Household", "Grid", "Government"]

ENERGY = [
    "Nuclear power",
    "Coal power baseload",
    "Gas power baseload",
    "Wind power",
    "Hydro power baseload",
    "Oil power baseload",
    "Other baseload",
    "Gas power peakload",
    "Hydro power peakload",
    "Oil power peakload",
    "Solar power",
]

energy_sam = [
    "Nuclear power",
    "Coal power",
    "Gas power",
    "Wind power",
    "Hydro power",
    "Oil power",
    "Solar power",
    "Other power",
]

AGR_CODES = [
    "PDR",
    "WHT",
    "GRO",
    "V_F",
    "OSD",
    "C_B",
    "PFB",
    "OCR",
    "CTL",
    "OAP",
    "RMK",
    "WOL",
    "FRS",
    "CMT",
    "OMT",
    "VOL",
    "MIL",
    "PCR",
    "SGR",
    "OFD",
    "B_T",
]

MFG_CODES = [
    "FSH",
    "COA",
    "OIL",
    "GAS",
    "OXT",
    "TEX",
    "WAP",
    "LEA",
    "LUM",
    "PPP",
    "P_C",
    "CHM",
    "BPH",
    "RPP",
    "NMM",
    "I_S",
    "NFM",
    "FMP",
    "ELE",
    "EEQ",
    "OME",
    "MVH",
    "OTN",
    "OMF",
]

SERV_CODES = [
    #     "ELY",
    "TnD",
    "GDT",
    "WTR",
    "CNS",
    "TRD",
    "AFS",
    "OTP",
    "WTP",
    "ATP",
    "WHS",
    "CMN",
    "OFI",
    "INS",
    "RSA",
    "OBS",
    "ROS",
    "OSG",
    "EDU",
    "HHT",
    "DWE",
]
