name: cge-dev
channels:
  - conda-forge
dependencies:
  # Base dependencies
  - python=3.12
  - jupyter
  - pip
  - numpy
  - scipy
  - sympy
  - pandas
  - numba
  - IPython
  - pymc
  - pytensor
  - tqdm
  - numba-progress
  - fastprogress
  - matplotlib
  - joblib

  # JAX Backend
  - jax
  - numpyro
  - blackjax

  - pip:
      - texttable
      - latextable
      - squarify
      - jupyter_contrib_nbextensions
      - jupyter_nbextensions_configurator
      - sympytensor


  # For building docs
  - ipython
  - jupyter-sphinx
  - myst-nb
  - numpydoc
  - pre-commit
  - sphinx>=5
  - sphinx-copybutton
  - sphinx-design
  - sphinx-notfound-page
  - sphinx-sitemap
  - sphinx-codeautolink
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme
  - watermark

  # developer tools
  - pre-commit
  - pytest
  - pytest-env
  - pytest-cov
