name: cge-modeling
channels:
  - conda-forge
dependencies:
  # Base dependencies
  - python=3.12
  - pip
  - numpy
  - scipy
  - sympy>=1.14.0
  - pandas
  - numba
  - pytensor
  - tqdm
  - numba-progress
  - matplotlib
  - jax
  - joblib
  - cvxpy

  - sympytensor>=1.3.3
  - better-optimize>=0.1.2

  - pip:
      - texttable
      - latextable
      - squarify
