name: cge-modeling
channels:
  - conda-forge
dependencies:
  # Base dependencies
  - python=3.12
  - pip
  - numpy
  - scipy
  - sympy<1.13
  - pandas
  - numba
  - pytensor
  - tqdm
  - numba-progress
  - fastprogress
  - matplotlib
  - jax
  - joblib
  - cvxpy

  - pip:
      - texttable
      - latextable
      - squarify
      - sympytensor
      - better_optimize
