name: geconpy-docs
channels:
  - conda-forge
dependencies:
  # Base dependencies
  - pip
  - numpy
  - scipy
  - sympy>=1.14.0
  - pandas
  - numba
  - IPython
  - pymc
  - pytensor
  - tqdm
  - numba-progress
  - matplotlib
  - joblib
  - cvxpy

  - sympytensor>=1.3.3
  - better-optimize>=0.1.2

  - pip:
    - latextable
    - texttable
    - squarify

  # Extra dependencies for docs build
  - ipython
  - jupyter-sphinx
  - myst-nb
  - numpydoc
  - pre-commit
  - sphinx>=5
  - sphinx-copybutton
  - sphinx-design
  - sphinx-notfound-page
  - sphinx-sitemap
  - sphinx-codeautolink
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme
  - watermark
