name: run_tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            python-version: "3.12"
          - os: windows-latest
            python-version: "3.11"
        test-subset:
          - |
            tests/

    runs-on: ${{ matrix.os }}

    env:
      TEST_SUBSET: ${{ matrix.test-subset }}

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: conda_envs/cge_test.yml
        create-args: >-
          python=${{matrix.python-version}}
        environment-name: cge-test
        init-shell: bash
        cache-environment: true

    - name: Install current branch
      run: |
        pip install -e .
        python --version

    - name: Run tests
      run: |
        python -m pytest -vv --cov=cge_modeling --cov-report=xml --no-cov-on-fail --cov-report term $TEST_SUBSET

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # use token for more robust uploads
        env_vars: TEST_SUBSET
        name: ${{ matrix.os }}
        fail_ci_if_error: false
        verbose: true
